### ISSUE TITLE
Does not work on iPad ios9 

### ISSUE THREAD

**Issue by Isodie** [WeCodePixels/theia-sticky-sidebar#15] opened 2015-12-28 16:34 UTC
The plugin shows slow response behavior in safari iPad ios9

**Comment by arun-maddheshia** [comment] 2016-02-05 12:30
please fix it soon it calculate height very slow in macbook safari

**Comment by liviucmg** [comment] 2016-02-05 14:09
At the moment I do not have time to take on this issue, but a possible work-around might be to disable inertial scrolling on iOS: http://stackoverflow.com/a/33311860/148388 . Pull requests are of course welcomed.

**Comment by liviucmg** [comment] 2016-11-22 19:22
Duplicate of #28

**Closed by liviucmg** 2016-11-22 19:22 UTC
Labels: bug, duplicate
