### ISSUE TITLE
Disable sticky menu in jquery

### ISSUE THREAD

**Issue by mmalekshahi** [WeCodePixels/theia-sticky-sidebar#66] opened 2020-04-02 14:00 UTC
Hi sir,
Is there any option or command to disable a sticky menu after running your plugin. something like this :
$('XXX').theiaStickySidebar().exit() or disable()
most tour generator plugins don't work properly when sticky menu is activated. I need to disable the sticky menu before run my tour plugin. Is there any way to do it?

**Comment by liviucmg** [comment] 2020-04-02 15:18
Hi there, unfortunately this is not implemented at the moment. Closing as duplicate of #31.

**Closed by liviucmg** 2020-04-02 15:18 UTC
